services:
  postgres:
    image: postgres:17
    container_name: byter-code-db

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: byte-coder

    ports:
      - "5432:5432"

    volumes:
      - byter-code-data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  byter-code-data: